//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisResult
    {
        public int ResultId { get; set; }
        public string PolicyNumber { get; set; }
        public int AnalysisId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ResultDate { get; set; }
        public string StatusRU { get; set; }
        public string StatusBA { get; set; }
        public string Details { get; set; }
        public string DoctorComment { get; set; }
    
        public virtual AnalysisType AnalysisType { get; set; }
    }
}
