//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthMetric
    {
        public int MetricId { get; set; }
        public string PolicyNumber { get; set; }
        public string MetricType { get; set; }
        public decimal Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public System.DateTime MeasureDate { get; set; }
        public string Comment { get; set; }
    }
}
