//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeVisit
    {
        public int VisitId { get; set; }
        public string PolicyNumber { get; set; }
        public string PatientName { get; set; }
        public string Address { get; set; }
        public string Symptoms { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
