//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YanaulCRBEntities2 : DbContext
    {
        public YanaulCRBEntities2()
            : base("name=YanaulCRBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalysisResult> AnalysisResults { get; set; }
        public virtual DbSet<AnalysisType> AnalysisTypes { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorPhoto> DoctorPhotoes { get; set; }
        public virtual DbSet<HealthMetric> HealthMetrics { get; set; }
        public virtual DbSet<HomeVisit> HomeVisits { get; set; }
        public virtual DbSet<MedicalCard> MedicalCards { get; set; }
        public virtual DbSet<PatientPhoto> PatientPhotos { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<SymptomRule> SymptomRules { get; set; }
        public virtual DbSet<TriageRecord> TriageRecords { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vaccine> Vaccines { get; set; }
        public virtual DbSet<VirtualQueue> VirtualQueues { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Vaccination> Vaccinations { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<SickLeave> SickLeaves { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
