//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPhoto
    {
        public int PhotoId { get; set; }
        public string PolicyNumber { get; set; }
        public string PhotoUrl { get; set; }
        public byte[] PhotoData { get; set; }
        public string PhotoType { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
