//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionId { get; set; }
        public string PolicyNumber { get; set; }
        public int DoctorId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string Medicines { get; set; }
        public string DosageInstructions { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public string Status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
