//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriageRecord
    {
        public int RecordId { get; set; }
        public string PolicyNumber { get; set; }
        public string UserInput { get; set; }
        public string DetectedSymptoms { get; set; }
        public string RecommendedDoctorSpecialty { get; set; }
        public Nullable<int> RecommendedDoctorId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
