//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccine
    {
        public int VaccineId { get; set; }
        public string NameRU { get; set; }
        public string NameBA { get; set; }
        public string DescriptionRU { get; set; }
        public string DescriptionBA { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public string AgeRestrictions { get; set; }
        public string Availability { get; set; }
        public Nullable<int> NextDoseDays { get; set; }
    }
}
