//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public int VaccinationId { get; set; }
        public string PatientPolicy { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string VaccineName { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
        public Nullable<System.DateTime> NextVaccinationDate { get; set; }
        public string SeriesNumber { get; set; }
        public string CertificateUrl { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
