//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanaulKioskPerfect
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualQueue
    {
        public int QueueId { get; set; }
        public int AppointmentId { get; set; }
        public int QueuePosition { get; set; }
        public Nullable<int> EstimatedWaitMinutes { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Notified { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
